### ISSUE TITLE
Obsidian mobile の起動時間

### ISSUE THREAD

**Issue by Akiyam-hub** [tadashi-aikawa/obsidian-questions#10]
こんにちは
度々ブログの方を閲覧させていただいております
先日のデイリーノートに関する記事も見せていただきました

デイリーノートの使い方についてたいへん参考にさせていただきました

自分もプラグインをいくつか利用しメモを取ったり予定管理に活用させています

ただ自分のモバイル環境では obsidian の起動が5-10程かかっているのがメモを取る際に煩わしさを感じています

おそらく色々なプラグインを入れているせいですね...
Tadashi_MAMANさんは起動時間はどれくらいでしょうか?
後日ブログの方で追記という形でお答えしていただければ幸いです.

**Comment by tadashi-aikawa** [comment]
@Akiyam-hub 
記事をお読みいただきありがとうございます :)

Obsidian mobileの起動時間は大体一緒で **5～10秒程度** です。また、起動時にObsidian syncの同期を待つため、大体20～30秒くらいは見込むことが多いです。

とはいえ一度起動してしまえば、次はObsidian mobileをアクティブにするだけなので一瞬です。Obsidian syncの時間を待つので結局5秒くらいは待つことが多いですが😅

プラグインの数はかなり絞っていますが、10や20程度であればせいぜい2秒くらいだと思います。それよりはVaultのノートが多いことの方が要因になると思っています。重いプラグインを入れていなければですが...。

**Comment by Akiyam-hub** [comment]
ご返信ありがとうございます!

> プラグインの数はかなり絞っていますが、10や20程度であればせいぜい2秒くらいだと思います。それよりはVaultのノートが多いことの方が要因になると思っています。重いプラグインを入れていなければですが...。

自分もその後プラグインを整理したところそれぐらいになりました.
ファイル数も考えなければならないのですね...
今後ともプラグインの開発や記事をご期待しています.

**Comment by tadashi-aikawa** [comment]
> ファイル数も考えなければならないのですね...

私の場合、基本的に『ファイル』を検索粒度としているので、ファイル数を意図的に減らすようなことはしないと思います。

起動速度は『端末の処理速度』と『ファイルシステムからのファイルを読み込む時間』に影響するため、以下に注意するようにはしています。

- なるべくスペックのいい端末を使う
- 読み込みが遅いストレージを使わない (HDDなど。今はほぼSSDなのでここはあまり関係ないかも)
- 低速になるリスクがあるファイルシステムは使用しない (特に共有ドライブ)
