### ISSUE TITLE
モバイル版でのcssの取得方法

### ISSUE THREAD

**Issue by kazdonkai** [tadashi-aikawa/obsidian-questions#11]
デスクトップ版では、Developer ツールを起動すれば、各個所のcssを取得出来ますが、モバイル版ではどの様に取得すれば良いのでしょうか？
そもそも、モバイル版には、Developer ツールって有るのでしょうか？

**Comment by tadashi-aikawa** [comment]
@kazdonkai 
CSSの確認が目的でしたら、PCから `app.emulateMobile(true)` を使ったデバッグが楽だと思います。

> **Note**
> [📱Obsidian開発でモバイルデバッグ \- Minerva](https://minerva.mamansoft.net/Notes/%F0%9F%93%B1Obsidian%E9%96%8B%E7%99%BA%E3%81%A7%E3%83%A2%E3%83%90%E3%82%A4%E3%83%AB%E3%83%87%E3%83%90%E3%83%83%E3%82%B0)

通常のPCモードだと以下のように `.is-mobile` のCSSは存在しませんが...

![image](https://github.com/tadashi-aikawa/obsidian-questions/assets/9500018/9adce02e-005c-41f7-ab17-9f23f3747ed3)

`app.emulateMobile(true)` でモバイルモードにすると出現しますので、CSSの取得や調整はできると思います。

![image](https://github.com/tadashi-aikawa/obsidian-questions/assets/9500018/37a5dca6-8771-479d-ae0d-d8dcc768d749)

**Comment by kazdonkai** [comment]
厄介なんですね😅
しかも、私の場合は、iPad Mac の組み合わせなので・・・
で、android と同じようにできるか、Macに接続してやろうとして見たのですが、出来ませんでした。

モバイル用のデフォルトのcssファイルとかないのだろうか？

**Comment by tadashi-aikawa** [comment]
@kazdonkai 

> 、iPad Mac の組み合わせ

Macから上でコメントしました方法ではダメでしょうか?

![image](https://github.com/tadashi-aikawa/obsidian-questions/assets/9500018/34ecbd88-d4b7-4226-b772-9175f111155e)

※ Androidのやり方は今回の方法とは無関係と思いましたので、コメントはしませんでした

**Comment by kazdonkai** [comment]
ん？
ちゃんと解っていないのですが、MacのObsidianでDeveloper Tools を開くということですか？
もしそうだとすると, 「Console で、app.emulate Mobile(mobile)を実行する」というのがどうすれば良いのか分かりません。
Console は開きましたが・・
Filterに入力？と言うレベルで、全くシロウトなので😅
すみません。

**Comment by tadashi-aikawa** [comment]
@kazdonkai 

> MacのObsidianでDeveloper Tools を開くということですか？

はい。

> Console は開きましたが

そこから以下のように入力して `Enter` 押すと、ObsidianがモバイルUIで再起動すると思います。

https://github.com/tadashi-aikawa/obsidian-questions/assets/9500018/64f38eac-8fe9-48e4-8735-48d930b60376

**Comment by kazdonkai** [comment]
ウーン，コマンドを入力する画面はどうやって出るんでしょうか😅
<img width="551" alt="スクリーンショット 2023-10-09 22 33 01" src="https://github.com/tadashi-aikawa/obsidian-questions/assets/90127278/02ead12a-8c7a-4230-98af-4f3343fbdbf0">

**Comment by tadashi-aikawa** [comment]
@kazdonkai 
スクロールバーを一番下まで移動する(①)か、コンソールクリアボタン(②)を押せば出ると思います。

![image](https://github.com/tadashi-aikawa/obsidian-questions/assets/9500018/b70637cc-0246-4265-808f-1df7452d5b7d)

**Comment by kazdonkai** [comment]
②でモバイル版に切り替わりました😘

つまり、
デスクトップ上のObsidianでデベロッパーツールを使って、モバイル版に切り替えて、エミュレートする。
という事なんですね。やっと理解できました。

これからCSSを調べてみます。
また、これについて何かあったら質問します。
取りあえず、ありがとうございました。

**Comment by tadashi-aikawa** [comment]
> デスクトップ上のObsidianでデベロッパーツールを使って、モバイル版に切り替えて、エミュレートする。

はい。その通りです 👍 

たしかに [📱Obsidian開発でモバイルデバッグ - Minerva](https://minerva.mamansoft.net/Notes/%F0%9F%93%B1Obsidian%E9%96%8B%E7%99%BA%E3%81%A7%E3%83%A2%E3%83%90%E3%82%A4%E3%83%AB%E3%83%87%E3%83%90%E3%83%83%E3%82%B0) の記述だとそうとも読み取れますね。。ちょっと言葉を補っておきます。

**Comment by tadashi-aikawa** [comment]
表題は『モバイル版でのcssの取得方法』となっておりますので、取得に関して問題なければクローズいただければと思います。(CSS自体に関するご質問は別のIssueでお受けします)

『モバイル版でのcssの取得方法』に関してまだ未解決課題がありましたら、このままで問題ありません 👍

**Comment by tadashi-aikawa** [comment]
@kazdonkai 
前より誤解の内容に書き直しましたので、よろしければご覧ください。

https://x.com/Tadashi_MAMAN/status/1711391094288892275?s=20
