### ISSUE TITLE
Headingのボーダーラインを文字数に合わせて表示する方法について

### ISSUE THREAD

**Issue by blacktanktop** [tadashi-aikawa/obsidian-questions#12]
Minervaを参考にして、自身のObsidian上の見た目のカスタイマイズをしております。

現在選んでいるテーマですとHeadingにボーダーラインがH2のみしかでません。
H3以降もボーダーラインを出したいと思っていると思っておりますが、表示幅いっぱいに表示するのではなく文字数に合わせて動的に行いたいと思っております。

Minervaではこれが実現されていると思っております。

どこかの情報を参考にして以下のようなjavascriptを使うことができれば可能なのではないかと思っておりますが、どこに配置するべきかも分からないため教えていただけないでしょうか？
```javascript
  const headingElement = document.getElementById('heading');
  const textLength = headingElement.textContent.length;
  const borderWidth = textLength
  headingElement.style.borderBottomWidth = `${borderWidth}px`;
```

**Comment by tadashi-aikawa** [comment]
@blacktanktop 
JavaScriptは不要です。CSSのみで対応できます。

以下にまとめましたので、そちらをご覧ください。

https://minerva.mamansoft.net/%F0%9F%93%97Obsidian%E9%80%86%E5%BC%95%E3%81%8D%E3%83%AC%E3%82%B7%E3%83%94/%F0%9F%93%97%E8%A6%8B%E5%87%BA%E3%81%97(%E3%83%98%E3%83%83%E3%83%80)%E3%81%AE%E4%B8%8B%E3%81%AB%E6%96%87%E5%AD%97%E6%95%B0%E3%81%AB%E3%81%82%E3%82%8F%E3%81%9B%E3%81%9F%E9%95%B7%E3%81%95%E3%81%AE%E4%B8%8B%E7%B7%9A(border)%E3%82%92%E8%A1%A8%E7%A4%BA%E3%81%97%E3%81%9F%E3%81%84

**Comment by blacktanktop** [comment]
ありがとうございます。
無事に設定することができました。

特にこのままでもいいと思っているのですが、単純な興味としてお伺いします。
Reading viewとEditing viewでは下線の色が変わるようです。
Reading viewのときは自動的に文字の色に合わせた下線にはならないものなのでしょうか？
（Thingsの影響で自動的につくH2の下線の存在も微妙に気になりますね・・・）

# Editing view
![Editing view](https://github.com/tadashi-aikawa/obsidian-questions/assets/7370243/93c554d2-2115-4a4b-a18f-911971b7c3a4)
# Reading view
![Reading view](https://github.com/tadashi-aikawa/obsidian-questions/assets/7370243/575a945b-a46b-4bda-8e0c-6a8ecee5003e)

**Comment by tadashi-aikawa** [comment]
@blacktanktop 

> Reading viewのときは自動的に文字の色に合わせた下線にはならないものなのでしょうか？

CSSの色設定にあわせてborderの色を設定するのがいいと思います。たとえば、見出し2がリンクになっている場合に下線を赤色にしたい場合は以下のようになります。

```css
.markdown-preview-view h2 .internal-link {
  border-bottom: 2px solid red;
}
```

私の場合、見出しのリンクには(aタグの)下線を表示したくないので以下のように設定しています。(色は設定していません)

```css
.markdown-preview-view h2 .internal-link {
  text-decoration: none;
}
```

**Comment by blacktanktop** [comment]
なるほど。ありがとうございます。
こちらで対応できました。
丁寧に解説していただきありがとうございました。
