### ISSUE TITLE
Obsidianのタイトルと本文をコピーし、かつ、ダブルブラケットとタグを削除

### ISSUE THREAD

**Issue by odayakata** [tadashi-aikawa/obsidian-questions#14]
𝕏で教えていただいた以下のコードを試したら、最初はエラーが出たのですが、無事できました！私のコピペがおかしく変な空白ができていました。ありがとうございました。

ちなみに、もし、ご存知でしたらご教授いただきたいのですが、このクリップボードに入ったデータをMac・iPad・iPhoneアプリ「Drafts」の新規ノートとして作成したいのですが、どこにコードを加えたらよいのでしょうか？

Draftsのアドレススキームはこれです→drafts://x-callback-url/create?text=Hello%20World

Obsidianと関係ない話ですいません。
もしおわかりでしたら、また、お手間をとらせない程度で教えていただけましたらありがたいです。
もしできなくても、ここまで教えていただいて便利になったので、あとは手動でがんばります。

小田やかた

<%* 
const f = app.workspace.getActiveFile()
const title = f.basename
body = (await app.vault.cachedRead(f))
  .replace(/!?\[\[(.+?)\]\]/mg, "$1")
  .replace(/#[^\s#]+/mg, "")
await navigator.clipboard.writeText(`${title}${body}`)
%>

**Comment by tadashi-aikawa** [comment]
@odayakata 
MacとDraftsがないので動作確認はできませんが...

> Draftsのアドレススキームはこれです→drafts://x-callback-url/create?text=Hello%20World

の `Hello%20World` 部分にクリップボードの内容を流したいなら以下のようになると思います。

※ クリップボードコピー部分は削除します

```
<%* 
const f = app.workspace.getActiveFile()
const title = f.basename
const body = (await app.vault.cachedRead(f))
  .replace(/!?\[\[(.+?)\]\]/mg, "$1")
  .replace(/#[^\s#]+/mg, "")
const text = `${title}${body}`

const uri = `drafts://x-callback-url/create?text=${encodeURIComponent(text)}`
window.open(uri, "_blank")
%>
```

**Comment by odayakata** [comment]
ありがとうございました！
どうもMacのDraftsは添付の画像の画面になり固まってしまいます。他のスクリプトでも同様なことが起きたのでMacではダメなようですね。iPhoneとiPadではうまくいきましたが。
勉強になりました。ありがとうございました。

https://gyazo.com/31e700cafed7f54cfcc9396f9eccf1b4

**Comment by tadashi-aikawa** [comment]
@odayakata 
確認されてるだけなので、下の方にスクロールするとボタンありませんか？ (Windowsでも出ます)

**Comment by odayakata** [comment]
ちなみに、クリップボードの中身を維持したまま、Draftsを開くだけの場合は
drafts://
をどこに入れたらよいのでしょうか？
手動で貼り付けようと思いまして。
（またまたObsidianとかけ離れてしまい恐縮です。）

**Comment by odayakata** [comment]
なぜかスクロールができないんですよね。

**Comment by tadashi-aikawa** [comment]
@odayakata 
長すぎるURIは考慮されてないかもしれませんね。本文が短いファイルでやるとどうなりますか？

**Comment by odayakata** [comment]
短い内容だと以下の画像になったので、「always open…」にチェックをいれることで、できるようになりました。いろいろありがとうございました！！
JavaScriptは、よくわからず、既存のものを組み合わせて何とかできるときもありますが、いずれ自分のやりたいことができるようにコードが書けるようになりたいです。

また、Obsidianで困ったら、このサイトを利用させてください！よろしくお願いします。

https://gyazo.com/7c3b0ce2d070bc7fe633fa6e58d85c8b

**Comment by tadashi-aikawa** [comment]
@odayakata 
期待通り動いたとのことでよかったです！

今回提示したコード含め、不明点ありましたらまたご質問いただければと。

このIssueはクローズします。
