### ISSUE TITLE
Various Complementsの確定ボタン

### ISSUE THREAD

**Issue by odayakata** [tadashi-aikawa/obsidian-questions#15]
Various Complementsでサジェストされた候補一覧から選ぶ（確定する）ボタンは、hotkeyのselectで設定できると思いますが、「Enter」以外は変更できないのでしょうか？
例えば、Commandやshiftを入れても反応しませんでした。

また、shift＋Enterにしたいのですが、この場合はどう入力したらよいのでしょうか？
半角を開けて並べたり、間に「,」を入れても反応しませんでした。

ご教授ください。

**Comment by tadashi-aikawa** [comment]
@odayakata 

> Various Complementsでサジェストされた候補一覧から選ぶ（確定する）ボタンは、hotkeyのselectで設定できる

はい。できます。

> 「Enter」以外は変更できないのでしょうか？

Enter以外に変更できます。

> 例えば、Commandやshiftを入れても反応しませんでした。
> また、shift＋Enterにしたいのですが、この場合はどう入力したらよいのでしょうか？

私の環境では `Shift Enter` で期待通り動きました。

[🎮 Copy plugin settings](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/3.%20Commands/%F0%9F%8E%AE%20Copy%20plugin%20settings/) でコピーした設定を共有していただくことはできますでしょうか?

あわせて、利用しているデバイス(OS)もお願いいたします。

**Comment by odayakata** [comment]
下記からコピペしたら動きました。
>私の環境では Shift Enter で期待通り動きました。

お騒がせして申し訳ありませんでした。
