### ISSUE TITLE
ChromeOSでのVarious Complementsのサジェストについて

### ISSUE THREAD

**Issue by neachi** [tadashi-aikawa/obsidian-questions#16]
素晴らしいプラグインの数々ありがとうございます。いつも重宝させていただいています…！

すみません、大変特殊な環境でのVarious Complementsのことでお尋ねしたいことがあります。
[環境]
OS：ChromeOS
アプリ：Android版のObsidian

現在、WindowsPC、スマホ、Chromebookの3デバイスでObsidianを使っているのですが、
Chromebookで「Android版のObsidian」を動かしています。
そこでVarious Complementsを使わせていただいているのですが、
この環境だと、日本語のワードに対して、サジェストが自動で出てきません。

説明が難しいので例を挙げますと、

---
[PC、スマホの場合]

「ブロッコリー」と文字入力すると「ブロッコリーの作り方」「ブロッコリーの産地」など、文字入力中に、vault内のノートをサジェストで自動で表示してくれます。

[Chromebookの場合]

「ブロッコリー」と文字入力しても、サジェストが何も表示されない。
ただし、以下の場合はサジェストが出てくれます
- 「ブロッコリー」と入力した後にBackspaceキーを押して「ブロッコリ」という風に文字を削るとサジェストが出てくれます
- また「ブロッコリー」と入力していき、サジェストキー`ctrl + space`を押すと、サジェストが出てくれます
- また日本語ワードではなく、英語で文字入力している際には自動で「英語のノート」をサジェストで表示してくれます

こういった感じで、日本語のワードでだけChromeOSの場合は、サジェストが自動で表示してくれないのです。
PCやスマホのそれぞれのVarious Complementsの設定を、そのままコピーしてみたり、
Various Complementsを一度消して、入れ直してみたり、設定を変えてみたり、
あれこれやっても自動でサジェストがでてくれないのですが、これはChromeOSの日本語文字入力の環境上、仕方ない感じなんでしょうか…？

すみません特殊な環境なので、お聞きするのも心苦しいなとは思ったのですが、何か解決する方法や糸口があれば、教えていただけたら…と思いましてこちらにissueを建てさせていただきました。

**Comment by tadashi-aikawa** [comment]
@neachi 
Chromebook環境はないため、こちらで再現確認調査は難しそうですが、お手伝いいただけば原因の特定はできるかもしれません。

まず、他プラグインやObsidianそのものの問題であるかどうかの切り分けをさせてください。

[📕Obsidianでエディターに関する不具合報告フロー \- Minerva](https://minerva.mamansoft.net/Notes/%F0%9F%93%95Obsidian%E3%81%A7%E3%82%A8%E3%83%87%E3%82%A3%E3%82%BF%E3%83%BC%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8B%E4%B8%8D%E5%85%B7%E5%90%88%E5%A0%B1%E5%91%8A%E3%83%95%E3%83%AD%E3%83%BC) に沿って確認お願いします。該当する質問に対して yes/no の回答もお願いします。

**Comment by tadashi-aikawa** [comment]
> CodeMirrorのサイトで再現するか?

については以下のように確認できます。『ブロッコリー』という関数を作って、そのあとで『ブロッコリー』と入力して補完が出ればOK

![image](https://github.com/tadashi-aikawa/obsidian-questions/assets/9500018/e5d50c2a-bf7c-43aa-a366-10a6fd955d67)

**Comment by neachi** [comment]
ありがとうございます！

早速、[📕Obsidianでエディターに関する不具合報告フロー - Minerva](https://minerva.mamansoft.net/Notes/%F0%9F%93%95Obsidian%E3%81%A7%E3%82%A8%E3%83%87%E3%82%A3%E3%82%BF%E3%83%BC%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8B%E4%B8%8D%E5%85%B7%E5%90%88%E5%A0%B1%E5%91%8A%E3%83%95%E3%83%AD%E3%83%BC)に従って確認してきました。

## Sandbox vaultで再現するか?
すみません！
ObsidianのAndroid版では、Sandbox vaultが用意されてないようで（ヘルプを開く コマンドを使うと help.obsidian.md に飛ばされてしまう）、なので、まっさらなvaultを用意して試してみました。

結果ですが、まっさらなVault上でも再現されました。

### 検証内容
1. Various Complementsプラグインのみインストール
デフォルト設定から`Strategy`を`japanese`に設定変更

2. テスト用のノートを作る
- ブロッコリーの作り方
- ブロッコリーの産地
- Broccoli for me
という3つのテストノートを作りました。
そして、改めて新しくノートを作り、そこでサジェストのテストを開始。

試してみたところ、やはり私のご相談していた挙動が再現されました。
（念のため、設定の`Strategy`を`default`でもやってみたましたが、同じでした）

「再現内容」
- 「ブロッコリー」と入力した後にBackspaceキーを押して「ブロッコリ」という風に文字を削るとサジェストが出てくれます
- また「ブロッコリー」と入力していき、サジェストキー`ctrl + space`を押すと、サジェストが出てくれます
- また日本語ワードではなく、英語で文字入力している際（Broccoli）には自動で「Broccoli for me」のノートをサジェストで表示してくれます

## 再現するのはVimモードONの場合のみか?
Vimモードは使っておらずOFFです。

## CodeMirrorのサイトで再現するか?
CodeMirrorで、教えていただいたコードでテストしてみたところ、CodeMirrorでも再現されました。

### 検証内容
CodeMirrorにて以下を入力
```
function hello(who = "world") {
  console.log(`Hello, ${who}!`)
}

function ブロッコリー () {}

ブロッコリー
```

- Chromebookで上記のコードを入力し、「ブロッコリー」と入力しましたが、何も補完は表示されませんでした
- 試しにPCとスマホで、同じコードを入力してCodeMirrorで試してみましたが、どちらも補完が表示されました

## Insider buildsか?
Insider buildsではないです。

Obsidianのバージョンは「1.4.16(114)」のAndroid版です。

---

CodeMirrorでの検証中に思ったのですが、Chromebookのキーボード入力のデフォルト設定だと、添付したスクショの様に、独自のサジェストが出るので、

![Screenshot 2023-11-01 14 34 40](https://github.com/tadashi-aikawa/obsidian-questions/assets/49504704/4dbb8ad1-d366-435d-99e0-d2cd59ac4336)

もしかしてこれが邪魔してるのでは…？と思い、Chromebookの「日本語入力の設定」からサジェストに関する設定をオフにして、Obsidian上でも、CodeMirror上でも試してみたのですが、変わらず再現する感じでした…。

![Screenshot 2023-11-01 14 35 29](https://github.com/tadashi-aikawa/obsidian-questions/assets/49504704/cca2258f-dcbd-4396-8622-c7a4a4e96cfb)

**Comment by tadashi-aikawa** [comment]
@neachi 
ご確認と報告ありがとうございます。状況についてよく分かりました。

CodeMirrorのサイトで再現するのであれば、こちらで何か対応することはほぼ不可能です。

(Obsidian... もっと言うとCodeMirrorのトリガーイベントが発動していないので判断ができないため)

IMEを変更して再現しない環境にしていただくしかないと思います。

※ Obsidianが正規対応しているIMEはおそらくMicrosoftIMEだけのはずです。私も10年近くATOK使っていましたが、ObsidianのためにIMEを変更したことがあったりします😅

**Comment by neachi** [comment]
ありがとうございます！

やっぱりそうなんですねー…
IME！と思い、私のChromebookがタブレットモードにでき、
タブレットモードの状態なら、AndroidのIMEアプリを入れて使うことができるので、AndroidアプリのGboardを入れてみて試してみたところ、Various Complementsのサジェストがちゃんと問題なく出ることを確認できました！

ただ、通常モードのChromebookの場合、特殊な方法でないとIMEを変更できないようにできているみたいなのと、相性が悪いのか常用できないような変な挙動になってしまうので、Chromebookの方では`ctrl + space`でサジェスト出すのを癖付けようかと思います。

自分の設定内容の見落としかなー…といろいろ悩んでいたので、すごくすっきりしました。
すごく特殊な環境なのに、ご回答いただきまして本当にありがとうございました…！

最後に、
Various Complements、Another Quick Switcher、Silhouetteと、これらのプラグインがあるからこそ、私がObsidianを使い続けてる理由のひとつでもあり、aikawaさんには本当に感謝しています。
これからも便利に使わせていただきます！
