### ISSUE TITLE
SilhouetteにおけるPCとモバイルの同期の不具合

### ISSUE THREAD

**Issue by Akiyam-hub** [tadashi-aikawa/obsidian-questions#17]
こんにちは,いつもプラグインを利用させていただいております.

Silhouetteについても一日のログを作成するために利用させていただいております.

以前アップデートによりPCとMoblieの間で計測中の時間を動悸する機能を追加したと思いますが,現在のバージョンでは同期ができませんでした.

お手数おかけしますが再度問題が無いか確認していただけますか?

お時間空いたときにご対応していただければ幸いです.

- Moblie::ver 1.4.16
- Desktop::ver 1.5.3
- OS::MacOS (ventura13.6.1)

**Comment by tadashi-aikawa** [comment]
@Akiyam-hub 
確認しました。以下2つのケースについて、私の手元では正常に動作いたします。

`ケース1`

1. PCで計測開始
2. モバイルで計測中であることを確認
3. モバイルで計測終了し、時間が表示される
4. PCでも時間が表示されている

`ケース2`

1. モバイルで計測開始
2. PCで計測中であることを確認
3. PCで計測終了し、時間が表示される
4. モバイルでも時間が表示されている

可能でしたら `.obsidian/plugins/silhouette` 配下の `data.json` の中身を教えていただけますでしょうか?

`私の場合`
```
{
  "taskFilePath": "_Privates/repeatable tasks.md",
  "holidayFilePath": "_Privates/holidays.md",
  "fileDateFormat": "",
  "timerStorageFilePath": "_Privates/timer.json",
  "startNextTaskAutomaticallyAfterDone": false
}
```

**Comment by Akiyam-hub** [comment]
ご返信ありがとうございます.

確認したところ以下のようになっています.

```
{
  "taskFilePath": "private/MyTaskfile.md",
  "holidayFilePath": "private/MyHoliday.md",
  "fileDateFormat": "YYYY-MM-DD",
  "timerStorageFilePath": "",
  "startNextTaskAutomaticallyAfterDone": false
}
```

**Comment by tadashi-aikawa** [comment]
@Akiyam-hub 
`.obsidian/plugins/silhouette/timer.json` が同期対象になっているかご確認いただけますでしょうか。

【参考】
https://github.com/tadashi-aikawa/silhouette?tab=readme-ov-file#%E8%A8%88%E6%B8%AC%E7%8A%B6%E6%85%8B%E3%82%92%E8%A8%98%E9%8C%B2%E3%81%97%E3%81%9Fjson%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AE%E3%83%91%E3%82%B9

**Comment by Akiyam-hub** [comment]
ご連絡ありがとうございます.
Syncの設定でPCとmoblieのプラグイン同士の同期をoffにしていたことが原因でした.

そちらを同期対象にしたことで解決しました.

引き続きプラグインが開発されることを期待しています!

**Comment by tadashi-aikawa** [comment]
@Akiyam-hub 
ご確認ありがとうございます。

もしプラグインを同期したくない場合は `計測状態を記録したJSONファイルのパス` (↑で共有したURL参照) でVault内の適当なパスを指定していただければと思います。
