### ISSUE TITLE
obsidian publishにて、独自ドメインを設定したものの、ページがつながらない。

### ISSUE THREAD

**Issue by wednes78** [tadashi-aikawa/obsidian-questions#2]
twitterのやりとりからこちらに移行させて頂きます（誘導ありがとうございました）。

https://minerva.mamansoft.net/Notes/Obsidian+Publish%E3%81%A7%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E3%83%89%E3%83%A1%E3%82%A4%E3%83%B3%E3%82%92%E6%8C%87%E5%AE%9A

こちらの記事を参考に、

obsidian publishにて取得したサイトを独自ドメインに移す方法を試していますが、現在独自ドメインURLが全くつながらない状況です。

独自ドメインをconoha wingにて取得し、cloud flareのネームサーバをconoha wingの管理画面から設定。obsidian publish の管理画面にて独自ドメインを設定済み。

DNSが浸透していない？可能性を考慮し、待つこと大体2０時間近くですが、いまだに独自ドメインのURLがつながっていない状況です。

解決にお力添えいただけないでしょうか。この情報を貼ってほしい等いただければスクショ等にてアップしますので、ご教示ください。

**Comment by tadashi-aikawa** [comment]
@wednes78 
作成ありがとうございます。私の環境からもdigでCloudflareのDNSが利用されていることは確認できました。

```
$ dig garden-kiryuhaya.com

; <<>> DiG 9.16.30 <<>> garden-kiryuhaya.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40352
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;garden-kiryuhaya.com.          IN      A

;; AUTHORITY SECTION:
garden-kiryuhaya.com.   1800    IN      SOA     matt.ns.cloudflare.com. dns.cloudflare.com. 2311860040 10000 2400 604800 1800

;; Query time: 43 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sun Jun 11 11:29:00 ;; MSG SIZE  rcvd: 108
```

> ;; AUTHORITY SECTION:
> garden-kiryuhaya.com.   1800    IN      SOA     matt.ns.cloudflare.com. dns.cloudflare.com. 2311860040 10000 2400 604800 1800

DNSの伝播時間は24～72時間と言われることが多いので、20時間ですと世界中のDNSサーバーに設定が行き届いていないだけの可能性は高そうです。

`garden-kiryuhaya.com` にはじめてアクセスした私の環境でも `DNS_PROBE_FINISHED_NXDOMAIN` となったため、ブラウザキャッシュである可能性は低いと思います。

他に原因があるとしたらCloudflareの設定そのものに問題があるケースです。DNSの設定画面を共有いただけますか?

参考までに私の設定は以下のようになっています。

![image](https://github.com/tadashi-aikawa/obsidian-questions/assets/9500018/59cd365d-6487-443d-925a-61f889629867)

**Comment by wednes78** [comment]
お返事ありがとうございます。

先ほど再度URLに繋いだところ、publishしたページが表示されました。

表示が安定しているので、おっしゃるように24時間以上経過してDNSがやっと浸透されたのだと思います。

親身になって原因を探っていただき、誠にありがとうございました。

**Comment by tadashi-aikawa** [comment]
@wednes78 
解決したとのことで良かったです👍 

そして、ドメインを garden-kiryuhaya.com と勘違いしていました... notes.garden-kiryuhaya.com には接続できました。(今朝の時点では分からないですが...)
