### ISSUE TITLE
Various complementで補完プロンプトを手動で起動できますか?

### ISSUE THREAD

**Issue by yo-goto** [tadashi-aikawa/obsidian-questions#3]
VSCodeには `Ctrl+Space` キーで Trigger Suggestionという補完を自分のタイミングで起動することができる機能があるのですが、[Various Complements](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin) ではそのような機能はありますか? `[[` でObsidianのデフォルトの補完が効きますが、自分でノートがあるかないかわからないときなどそのまま入力を `[[` を削除するようなことなく入力を続けられると良い気がしています。

参考: https://zenn.dev/hiroga/articles/vscode-trigger-suggestion-macos

**Comment by tadashi-aikawa** [comment]
@yo-goto 
[Show suggestions](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/3.%20Commands/%F0%9F%8E%AE%20Show%20suggestions/)コマンドがそれにあたります。

デフォルトは `Mod + Space` なので Windowsなら `Ctrl + Space` で発動すると思います。

**Comment by yo-goto** [comment]
できました👍
ありがとうございます~
