### ISSUE TITLE
モバイル版Another Quick Switcherでの Dialog

### ISSUE THREAD

**Issue by ginjiro** [tadashi-aikawa/obsidian-questions#4]
Another Quick Switcherを使わせてもらってます。
検索結果からのDialogでinsert to editerが大変便利です。
モバイル版でもMain Dialogを使いたいのですが、実装予定はありますでしょうか？

**Comment by tadashi-aikawa** [comment]
@ginjiro
ご利用ありがとうございます<(_ _)>

> モバイル版でもMain Dialogを使いたい

Main Dialogとは何を指していますでしょうか?  Another Quick Switcherは基本的にモバイルにも対応しております。

**Comment by ginjiro** [comment]
お返事ありがとうございます

検索結果からの Dialogで
Windowsなら、alt + enter で内部リンクを挿入できますが
モバイル版では、下記のように検索結果からノートを開くことしかできません。
デスクトップ版のようにモバイル版でも、insert to editer で内部リンクを挿入したいです。

[![Image from Gyazo](https://i.gyazo.com/b8a29d80810c50375c2c089cf136aa7e.gif)](https://gyazo.com/b8a29d80810c50375c2c089cf136aa7e)

**Comment by tadashi-aikawa** [comment]
@ginjiro 
詳細ありがとうございます。スマートフォンからの操作ということですね。

今のところ、上記機能の実装予定はありません。理由は以下の通りです。

- (今までに) 要望がなく、個人的にも利用していない
- Another Quick Switcherのメイン機能ではない
    -  リンク挿入をメインで行いたい場合は [Various Complements](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin) を使った方がよい
- スマートフォン版ではキーボードのショートカットが使えないため実装が難しい (はず)

**Comment by ginjiro** [comment]
返信ありがとうございます。

> Another Quick Switcherのメイン機能ではない

Various Complements も利用させてもらってますので、使い倒せるようやり方を見直してみます。

> スマートフォン版ではキーボードのショートカットが使えないため実装が難しい (はず)

ショートカットキーではなくなりますが、検索結果のノートリストから個別ノートの長押しでメニューが出せるとかよさそう

Various Complementsでやりたいことはできそうとのことなのでやってみます。

**Comment by tadashi-aikawa** [comment]
@ginjiro 
よろしくお願いいたします。

Obsidian mobileの長押しは、APIを見る限り実現は厳しそうに見えます。もし実装するとしたら、リストの右端にFloatingボタンを配置するか、リストの下にアクションボタンを配置するかになると思います。オプションで有効にした場合のみ。

Various Complementsでは実現が厳しいユースケースがありましたらフィードバックいただければ、いずれかの対応を致します。

- Various Complementsで実現可能なら、その具体的な手順を共有
- Various Complementsで実現不可能なら、Another Quick Switcherへの機能追加を検討

**Comment by tadashi-aikawa** [comment]
最後のコメントから1ヶ月以上経過しているため、本Issueはクローズさせていただきます。(必要に応じてreopenしてください)
