### ISSUE TITLE
はじめまして。このたび初めてこの場を知りました。

### ISSUE THREAD

**Issue by dlphnkck** [tadashi-aikawa/obsidian-questions#5]
こんにちは。はじめまして。このたび初めてこの場を知りました。日本語で投稿できるフォーラムが少ないので、日本語でそのまま投稿できるこういった場は貴重だと思います。貴重な機会なので、できるだけ、利用させて頂きたいと思っています。

- Discord の日本語チャンネルは過疎化している印象（と思ったら、今見たらObsidianの利用者が増えたのか、活気が。）
- Twitterは速報性などフローを流すには便利ですが、情報がストックされないので。

※英語のGitHubに投稿する場合だと、元の日本文を英訳して、さらに世界中の万人に伝わるように、英文チェッカーをかけたりして、日本語の2倍の手間をかけているので。

**Comment by tadashi-aikawa** [comment]
@dlphnkck 
はじめまして。書き込みありがとうございます。

Obsidianの利用人口からして、どうしても英語のやりとりがMustになってしまうのですが、私も英語でのやりとりに結構心理的負担が発生しておりまして、何も考えずにつらつら書ける場が欲しいなと作ってみました。

よろしくお願いいたします😀

**Comment by tadashi-aikawa** [comment]
最後のコメントから1ヶ月以上経過しているため、本Issueはクローズさせていただきます。(必要に応じてreopenしてください)
