### ISSUE TITLE
「表記ゆれ」にFront Fomatter の aliases を使うか、使わないか？

### ISSUE THREAD

**Issue by dlphnkck** [tadashi-aikawa/obsidian-questions#6]
さて、本題です。tadashi-aikawa様は以前、Front Fomatter の aliases は「表記ゆれ」には使っていないと発言されていた記憶があります。

- "徳川家康"と"徳川 家康"
- "オードリー・タン"と"Audrey Tang"
- "VSCode"と"Visual Studio Code"

などの表記ゆれは別々のノートにしているということなのでしょうか？他の方は「表記ゆれ」に aliases を使われているのですか？

**Comment by tadashi-aikawa** [comment]
@dlphnkck 

> 「表記ゆれ」にFront Fomatter の aliases を使うか、使わないか？

こちらは『使っている』が回答となります。

> Front Fomatter の aliases は「表記ゆれ」には使っていないと発言されていた記憶

これは『内部リンクで表記ゆれのエイリアスを使うか?』に対して『使わない』という意味だと思います。たとえば

> "VSCode"と"Visual Studio Code"

の例だと `VSCode.md` を作成し、そのフロントマターは以下のようになります。

```
---
aliases:
  - "Visual Studio Code"
---
```

そして、実際に『VSCode』を内部リンクとして表現する場合は **常に `[[VSCode]]` と記載します**。言い換えると `[[VSCode|Visual Studio Code]]` と記載することはありません。

そのため、ノートの名称には **正式名称ではなく普段文章で使用する表現** を採用しています。

> 表記ゆれは別々のノートにしているということなのでしょうか？

上記から『別々のノートにはしていない』となります。

> 他の方は「表記ゆれ」に aliases を使われているのですか？

知る限り、私のようなaliasesの利用戦略はあまり目にしません。一般的には以下のケースをよく目にします。

- ノートには正式名称を書く
- aliasesには略称や揺らぎを書く
- 内部リンクでは文脈によって表現(正式名称 or aliases)を変える

**Comment by tadashi-aikawa** [comment]
最後のコメントから1ヶ月以上経過しているため、本Issueはクローズさせていただきます。(必要に応じてreopenしてください)
