### ISSUE TITLE
Various Complements プラグイン の日本語の場合の補完機能

### ISSUE THREAD

**Issue by dlphnkck** [tadashi-aikawa/obsidian-questions#7]
Various Complements プラグインですが、日本語の場合、

1. ブランケットで囲まなくても、たとえば、地の文の「今日はいい天気」と入力途中で補完機能が働くことを想定されていますか？
2. それとも「`[[`今日はいい天気」とブランケットを書いてから入力を始めることを想定されていますか？

1の場合、補完候補が表示されないときもあるので。

以上です。よろしくお願いいたします。

この場を発見して興奮していたので、最近の疑問を一気に書き込んでしまいました。
みなさま、お仕事の合間に開発だけではなく、保守もされていると思うので、お返事は急ぎません。
※これを英文に翻訳して投稿したら、どれだけ時間がかかることか……。

**Comment by tadashi-aikawa** [comment]
@dlphnkck 

> 1. ブランケットで囲まなくても、たとえば、地の文の「今日はいい天気」と入力途中で補完機能が働くことを想定されていますか？

こちらを想定しています。

> 1の場合、補完候補が表示されないときもあるので。

エッジケースでは (特に『の』まわり) 候補が表示されないケースもありますが、全体では1%くらいだと思っています。設定の問題や不具合かもしれませんので、再現手順を共有いただければ確認できます 👍

**Comment by tadashi-aikawa** [comment]
> この場を発見して興奮していたので、最近の疑問を一気に書き込んでしまいました。

匿名ではないせいかもしれませんが、現在あまり投稿がないので、遠慮なく話題提供いただけるとこちらも助かります 🙏

**Comment by tadashi-aikawa** [comment]
最後のコメントから1ヶ月以上経過しているため、本Issueはクローズさせていただきます。(必要に応じてreopenしてください)
