### ISSUE TITLE
Another Quick Switcher は Properties を検索対象とする計画がありますか？

### ISSUE THREAD

**Issue by d-fuchi** [tadashi-aikawa/obsidian-questions#8]
## 質問概要
Obsidian v1.4 から導入された Properties (≒frontmatter) について、Another Quick Switcher の検索対象とできるようなオプションを追加する方針（予定）があるでしょうか？

## 背景
まず私は普段から Another Quick Switcher を非常に頻繁に使わせてもらっており、これ無しでは Obisidan を使えないレベルです。開発いただいていることに非常に感謝しています🙏

Obsidian v1.4 から導入される Properties は私にとってなかなかのインパクトであり、かなり frontmatter の使い勝手が向上したので、今私は自分のノートルールを見直ししています。

その中で、検索で引っ掛けたいキーワードのようなものを Properties に配置することを検討していますが、今確認したところ AQS では frontmatter を検索対象にすることはできないように思いました。
（できるのであればすみません、その旨ご教示いただければ解決ですｗ）
できると嬉しいんですが、AQS がそもそも対応する気がないので考え直す必要があり。

こちら、今後検索対象のオプションにでも追加する予定があるかどうかが知れれば、ノートルールを考える際にそれを前提にして検討できるので嬉しいと思ってお尋ねさせていただきました。

よろしくお願い致します。

**Comment by tadashi-aikawa** [comment]
@d-fuchi 

> Properties (≒frontmatter) について、Another Quick Switcher の検索対象とできるようなオプションを追加する方針（予定）があるでしょうか？

明確な予定はありませんが、Feature Requestの量次第では対応したいと思っています。Propertiesの今後の状況にもよりますが...。

やるとしたら、今のところ、以下のいずれか (or 両方) を想定しています。

- `key:value` 形式のような絞り込み
- keyによらず、valueにヒットするかどうかの絞り込み

> その中で、検索で引っ掛けたいキーワードのようなものを Properties に配置することを検討していますが、今確認したところ AQS では frontmatter を検索対象にすることはできないように思いました。

任意のPropertiesの値で検索/ソートする機能はありません。今の機能では `aliases` や `tags` を有効にして、そこから拾うやり方しかできないと思います。(私はこの戦略をとっているため満足してしまってはいます...)

![image](https://github.com/tadashi-aikawa/obsidian-questions/assets/9500018/26c52639-da4b-4790-a558-73dff419056e)

![image](https://github.com/tadashi-aikawa/obsidian-questions/assets/9500018/c658c5e5-a076-4f58-8fa0-e4633d3a8b46)

少し話はそれますが、特定Propertiesの値でソートする機能 (Sort Prioritiesの追加) は近々実装しようと思っています。 `created` といった日付型の値でソートしたいことがしばしばありまして...。

**Comment by d-fuchi** [comment]
@tadashi-aikawa ご回答ありがとうございます！

>明確な予定はありませんが、Feature Requestの量次第では対応したいと思っています

承知しました。
そもそも公式リリースがまだですので先のことにはなると思いますが、個人的には

>keyによらず、valueにヒットするかどうかの絞り込み

ができるようになったら嬉しいなぁという1ユーザーの希望として挙げさせていただきます。
`Search by` に `Properties` を追加する感じがいいのかぁとか思ってみたり。

>今の機能では aliases や tags を有効にして、そこから拾うやり方しかできないと思います

ですよね。
基本的には Tag と Header はともに有効にして便利に使わさせてもらっています。

例えば表記ゆれに近いケースは元々 alias に詰め込んでいたんですが、検索で引っ掛けやすくすることを重要視しているので本来の alias とは異なる意味合いで利用することが増えてしまっていることが気になるようになってしまいました。どちらかというと私のは keyword 的なイメージでしたので。
それから今は個人的に header としては使わない h6 (=`######`) をページの末尾に付与して、そこに検索用ワードを付けるようにしています。 Search by で Header を ON にしているのでひっかかります。

また個人的に Tag と内部リンクの使い分けにちょっと迷うところがありまして。例えば Obsidian 関連のノートをまとめたいときに `#Obsidian` を使うのかのか `[[Obsidian]]`を使うのか、というところですね。
こちら決断できずにずっとダラダラとどちらも使い続けている状態でした（どちらもノートに付けるようにする）。

ここ最近は、固有名詞は内部リンクのほうがいいかなぁと思っているところがあったので、運用をそちらに寄せようとしていたところ、今回の Properties のリリースがあり、内部リンクが Properties で機能するようになったこともあってそこに内部リンクを記載するようにしてみたのですが、そうすると AQS でひっかからなくなっちゃって…というのが今回ご質問に至った経緯です。

ノート中に自然に内部リンクが入れられる場合はそれでいいんですけどね。
`[[Obsidian]]` というのが入れづらい場合などは Properties に category 的な key で入れちゃうのがきれいにまとまるかなと思ったため。

>特定Propertiesの値でソートする機能 (Sort Prioritiesの追加) は近々実装しようと思っています。 created といった日付型の値でソートしたいことがしばしばありまして...。

なるほど、ありがとうございます。
"重要性" みたいなのを Properties に持たせているのでそれは私にとってもうれしいです。
あ、でも日付型のみの予定だったらだめかもですが…ｗ

---
長々と失礼しました。
とりあえずふわっとした予定についてはイメージつきましたので、実装されなくてもぜんぜん困らない運用でしばらく続けます！ありがとうございます。

**Comment by tadashi-aikawa** [comment]
@d-fuchi 

> Search by に Properties を追加する感じがいいのかぁとか思ってみたり。

そうですね。恐らくそうなると思います。

また、解析対象のPropertiesは指定方式になると思います。すべてのPropertiesを解析対象にすると、indexingとsearchの双方で実行時間が伸びてしまい、体感で分かるくらい遅くなると思いますので...。

> 例えば表記ゆれに近いケースは元々 alias に詰め込んでいたんですが、検索で引っ掛けやすくすることを重要視しているので本来の alias とは異なる意味合いで利用することが増えてしまっていることが気になるようになってしまいました。どちらかというと私のは keyword 的なイメージでしたので。

私のaliasもそのような感じになってる部分はありますね。『手順』のようなタイトルがついていても、トラブルシューティングのような名称をaliasにつけることもあります。ただ可能な限り、手順とトラベルシューティングは別ページにして、トラベルシューティングから手順に誘導するようにはしています。(その誘導ページが実質的なキーワードの働きなのかもしれません)

おっしゃる通り、本来の使い方はあくまで『別名』なのですが、Obsidian Publishでも同じ体験できるように... と思うと、aliasはなかなか便利だったりします。タグや見出しでも検索は可能ではありますが。

> また個人的に Tag と内部リンクの使い分けにちょっと迷うところがありまして。例えば Obsidian 関連のノートをまとめたいときに #Obsidian を使うのかのか [[Obsidian]]を使うのか、というところですね。

これは私も結構フラフラしていましたし、今も若干迷いながら運用しています😅

ただ、基本的に内部リンクは検索用途を目的に使わないようにしています。そのため、検索用途でタグをつけることも多々あります。例外として、タイトルにその名称が含まれる場合はそちらで検索にヒットするため、タグはつけていません。

> **Note**
> [💿MIN\-0018 タイトルに含まれる項目のタグはつけない \- Minerva](https://minerva.mamansoft.net/%F0%9F%92%BFADR/%F0%9F%92%BFMIN-0018+%E3%82%BF%E3%82%A4%E3%83%88%E3%83%AB%E3%81%AB%E5%90%AB%E3%81%BE%E3%82%8C%E3%82%8B%E9%A0%85%E7%9B%AE%E3%81%AE%E3%82%BF%E3%82%B0%E3%81%AF%E3%81%A4%E3%81%91%E3%81%AA%E3%81%84)

プロパティ(フロントマター)でキーワードをひっかける方法も何度か検討したことあります...が、以下の理由で未だ見送っています。

- Obsidian Publishで検索できない (少なくとも今は)
- Another Quick Switcherで検索できない (少なくとも今は。こっちはやればできます)
- キーワードはタグでひっかけた方が色々便利そう

> "重要性" みたいなのを Properties に持たせているのでそれは私にとってもうれしいです。
> あ、でも日付型のみの予定だったらだめかもですが…ｗ

日付型を考慮する予定はありません。数値か文字列かくらいは見分けるようにすると思いますが...。

**Comment by tadashi-aikawa** [comment]
@d-fuchi 

> ここ最近は、固有名詞は内部リンクのほうがいいかなぁと思っているところがあったので、運用をそちらに寄せようとしていたところ、今回の Properties のリリースがあり、内部リンクが Properties で機能するようになったこともあってそこに内部リンクを記載するようにしてみたのですが、そうすると AQS でひっかからなくなっちゃって…

Another Quick Switcher 9.0.0-beta4 で Obsidian 1.4のサポートをしました。

https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/9.0.0-beta4

主に以下2点です。

- プロパティ内のリンクをさまざまな検索で認識するようになった
- プロパティ内にリンクがあると、そのリンク先ノートでバックリンク検索したときにエラーになる不具合が修正された

よろしければお試しください。

**Comment by d-fuchi** [comment]
@tadashi-aikawa 
>解析対象のPropertiesは指定方式になると思います。すべてのPropertiesを解析対象にすると、indexingとsearchの双方で実行時間が伸びてしまい、体感で分かるくらい遅くなると思いますので...。

はい、その方がよいと思います。なんでもかんでも検索対象になると逆にノイズにもなっちゃいそうですし、パフォーマンスに影響がありそうならなおさらそのとおりだと思います。

alias と内部リンクについてもコメントありがとうございます。非常に参考になります。
しっかり読み返しながら、自身の運用ルール決めのヒントにさせていただきます！
タグのルールについてちょっとキッチリしようとしすぎていたかもしれないです。
もうちょっと大雑把に「検索に上手に引っ掛けるためのツール」くらいの認識で使ってみるとやりやすいのかな、とも思ったりしました。
このあたり色々工夫の仕方があって個人の色がでるのがおもしろいところですね。

>プロパティ(フロントマター)でキーワードをひっかける方法も何度か検討したことあります...が、以下の理由で未だ見送っています。

なるほど、たしかに aikawa さんの場合 Publish の検索はかなり重要ですね。

>日付型を考慮する予定はありません。数値か文字列かくらいは見分けるようにすると思いますが...。

ありがとうございます。それは好都合でうれしいです。

>Another Quick Switcher 9.0.0-beta4 で Obsidian 1.4のサポートをしました。

こちらについても早速ありがとうございます！
スキマ時間に導入して試してみたいと思います！

**Comment by tadashi-aikawa** [comment]
最後のコメントから1ヶ月以上経過しているため、本Issueはクローズさせていただきます。(必要に応じてreopenしてください)

**Comment by tadashi-aikawa** [comment]
@d-fuchi 

> keyによらず、valueにヒットするかどうかの絞り込み

まだbetaですが 11.0.0 でリリース予定ですので共有させていただきます。
https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/227

※ 私は `description` と `created` で検索かけることが多いですね

**Comment by d-fuchi** [comment]
@tadashi-aikawa わざわざご連絡いただきありがとうございます！
幸運にもリリースされていたことにすぐ気づいたので BRAT で早々に利用させてもらってます！
いい具合に機能してとっても助かってます、ありがとうございます😄
